### PR TITLE
Add related resources panel to board sharing tab sidebar

### PR DESCRIPTION
**Pull request by Pytal**
### Requires

- [x] https://github.com/nextcloud/nextcloud-vue/pull/3081
- [x] Upgrade `@nextcloud/vue` >=7.0.0-beta.1

### CODE REVIEW

**Comment by juliushaertl** [comment]
vue lib bump is pending in https://github.com/nextcloud/deck/pull/3991

**Comment by juliushaertl** [comment]
The backend provider itself is the same as from the old projects feature or is it currently still in the related resource app?

**Comment by Pytal** [comment]
> The backend provider itself is the same as from the old projects feature or is it currently still in the related resource app?

The provider is https://github.com/nextcloud/related_resources/blob/cffb809b22c425aeeb6b88df2bd145722f94fe54/lib/RelatedResourceProviders/DeckRelatedResourceProvider.php in the related resources app

**Comment by juliushaertl** [comment]
Rebased on top of the merged vue components bump

**Comment by juliushaertl** [comment]
Yes, seems to work now without further action, just by waiting a bit

**Review by juliushaertl — APPROVED** [review]

**Comment by ArtificialOwl** [comment]
Yeah, so caching. do you generate an event on share creation/deletion so that the RelatedResources app can better manage the cache ?

https://github.com/nextcloud/related_resources/pull/46

**Pull request merged**
