### PR TITLE
IE11 Fixes

### PR DESCRIPTION
**Pull request by juliushaertl**
Commit cleanup of #267

### CODE REVIEW

**Comment by artemanufrij** [comment]
I can't test it on IE11. I'm using Archlinux here :smiling_imp:

**Comment by juliushaertl** [comment]
> I can't test it on IE11. I'm using Archlinux here ￼

Same over here. Ok, let's merge since i could not find any issue with Chromium/FF. :rocket:

**Comment by juliushaertl** [comment]
Thanks @jacestk :wink:

**Comment by jacestk** [comment]
Ok thanx for merging 📦 
Have to make some polyfix for IE11 working with Tasks app now...

**Pull request merged**
