### PR TITLE
Properly handle multiple shares in a row and refactor sharee loading

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes https://github.com/nextcloud/deck/issues/2086

In addition I'm adding some nicer loading feedback on the share input.

### CODE REVIEW

**Comment by MorrisJobke** [comment]
Bildschirmfoto 2020-10-09 um 16 06 31


I get "failed to add USER to share" but the user is added after a refresh 🤔

**Comment by juliushaertl** [comment]
Helps to remove debug statements for testing error cases. :see_no_evil: Could you please check again @MorrisJobke ?

**Review by MorrisJobke — APPROVED** [review]
Tested and works 👍

**Pull request merged**
