### PR TITLE
Fix CalDAV blocking and modernize circles API usage

### PR DESCRIPTION
**Pull request by juliushaertl**
- Avoid blocking calendar access if something goes wrong while fetching deck entries
- Move any circles API usage to internal service and make use of new circles API to get the list of circles for a user

* Resolves: #3312

### CODE REVIEW

**Comment by juliushaertl** [comment]
@ArtificialOwl https://github.com/nextcloud/deck/blob/81740c9404699cb956803c119c17b946b396f4a5/lib/Service/CirclesService.php#L56 is still using the old API, would the following work fine for replacing that? 

```php
		// Enforce current user condition since we always want the full list of members
		/** @var CirclesManager $circlesManager */
		$circlesManager = \OC::$server->get(CirclesManager::class);
		$circlesManager->startSuperSession();
		return $circlesManager->getCircle($circleId);
```

**Comment by ArtificialOwl** [comment]
> @ArtificialOwl
> 
> https://github.com/nextcloud/deck/blob/81740c9404699cb956803c119c17b946b396f4a5/lib/Service/CirclesService.php#L56
> is still using the old API, would the following work fine for replacing that?
> 
> ```
> 		// Enforce current user condition since we always want the full list of members
> 		/** @var CirclesManager $circlesManager */
> 		$circlesManager = \OC::$server->get(CirclesManager::class);
> 		$circlesManager->startSuperSession();
> 		return $circlesManager->getCircle($circleId);
> ```

It should work, however you need to be sure that the params in `getCircle(string $circleId)` are not fed by a user: https://github.com/nextcloud/deck/blob/81740c9404699cb956803c119c17b946b396f4a5/lib/Service/CirclesService.php#L51

**Review by ArtificialOwl — APPROVED** [review]

**Comment by ArtificialOwl** [comment]
not tested, but code looks good. 

The only comment I have is that after migration of `CirclesService::getCircle()` to the new API, the exception returned by the new API (if Circle is out of reach) will be managed by a `catch (Throwable)`

**Pull request merged**
