### PR TITLE
fix desc save bug

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>

* Resolves: #2789 
* Target version: master

### CODE REVIEW

**Comment by jakobroehrl** [comment]
@juliushaertl Could you look over this?

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
/backport 035e0c0fe8d864c431a31a38e58671df00730dcf to stable1.3

**Comment by juliushaertl** [comment]
/backport 035e0c0fe8d864c431a31a38e58671df00730dcf to stable1.1

**Pull request merged**
