### PR TITLE
This is part one of the style cleanup mentioned in #160.

### PR DESCRIPTION
**Pull request by pixelipo**
Functionality has not been affected (I hope). There will be few more related PRs but I want to keep each one simple so it's easy to review.

Created new template `headerControls.php` to prevent double code.

@artemanufrij not set as reviewer since "off-work" in the next few days :wink: 

Signed-off-by: Marin Treselj <marin@pixelipo.com>

### CODE REVIEW

**Comment by juliushaertl** [comment]
@pixelipo Just one small regression, the label of the create new stack form looks a bit to much on top:

2017-05-26-223201_313x56_scrot

Otherwise great :+1:

**Comment by pixelipo** [comment]
Should be ok now, @juliushaertl

**Comment by juliushaertl** [comment]
@pixelipo Signoff is missing on the last commit :wink:

**Comment by pixelipo** [comment]
@juliushaertl I signed it with a verified GPG key. That should be even better, right?

**Comment by juliushaertl** [comment]
@pixelipo Those are two different things. GPG signing allows to verify that you are the original author of the commit while the signoff message is there to approve that your contribution is under the same license as the project is.

**Comment by juliushaertl** [comment]
@pixelipo I've rebase this to master. Will be merged once CI is green. :+1:

**Comment by pixelipo** [comment]
Thanks @juliushaertl I'll make sure to use both `-s` and `-S` next time :wink:

**Comment by juliushaertl** [comment]
@pixelipo Git aliases are also great for that, so you don't need to type them every time.

**Pull request merged**
