### PR TITLE
click outside to close sidebar

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>

* Resolves: #1794
* Target version: master 

With this change the sidebar no longer opens at all. 
@juliushaertl do you have an idea how to solve it?

### CODE REVIEW

**Review by juliushaertl — CHANGES_REQUESTED** [review]
Doesn't work that easy, as this basically blocks the sidebar from being opened in the first run when clicking on a card.

**Comment by jakobroehrl** [comment]
@juliushaertl How to do this?
Would it be easier to implement closing with the esc key?

**Comment by juliushaertl** [comment]
Well escape key should probably also work but the click would be still useful. To make this work you would basically need to make sure that the click was triggered on the board dom element and not on a card in the v-click-outside handler.

**Comment by jakobroehrl** [comment]
It doesn't work with that either: Sidebar no longer opens
https://github.com/nextcloud/deck/blob/5e3661cd6a72af9d4ed2b1011e735d0d8f26171d/src/App.vue#L26

**Comment by marcelklehr** [comment]
> To make this work you would basically need to make sure that the click was triggered on the board dom element and not on a card in the v-click-outside handler.

Fixed by using @juliushaertl's approach :)

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Seems to have caused a regression when trying to open the board sidebar as that click opens the sidebar but closes it directly again. Maybe we should only trigger it when clicking the board content area somehow.

**Pull request merged**
