### PR TITLE
Change the word labels to tags for consistency

### PR DESCRIPTION
**Pull request by reginasipos**
I proposed this change because they're called tags everywhere else.

### CODE REVIEW

**Comment by jancborchardt** [comment]
Looks good to me! :) @nextcloud/deck can you check?

**Comment by pixelipo** [comment]
It seems to me that there are more places where 'label' is used (in part.card.php):
"Choose a label"
"Add a label"
"Select labels…"

It would be good to fix them all

**Comment by juliushaertl** [comment]
Makes sense. Thanks for your contribution, @reginasipos. As @pixelipo said, it would be great if you could change the other occurrences as well.

**Comment by reginasipos** [comment]
@pixelipo @juliushaertl fixed the others :)

**Comment by juliushaertl** [comment]
Signoff message is missing for commits, but let's merge, since it is a very small and language string only change.

**Comment by juliushaertl** [comment]
Thanks again @reginasipos

**Pull request merged**
