### PR TITLE
card collections/dashboard

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob <jakob.roehrl@web.de>
* Target version: vue

Added some collections, and it's working so far :)
Could you give me your feedback @juliushaertl ?

- There is now redundant code from the card view
- The Router could be better, I think
- Fetching the data is not really fast, should I try to solve this on the server or client side?
- Any ideas how to change the code, if we have filtering and searching in mind?

Thanks a lot! :)

I think I would use this view in #1315, too. 

grafik

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! :) Some design feedback:
- [ ] The counters of "Due soon" and "Assigned to you" should use the counter on the right of the row as defined in the component
- [ ] No categorization and indentation is needed. Simply do a flat list with
  > - Due soon
  > - Assigned to you (we always use "you", never "me" in the interface)
  > - All cards
  > `space`
  > - Board 1
  > - Board 2
  > - …

**Comment by ardarandir** [comment]
Hi, we would love this collections/dashboard feature to go live for productive use. I don't quite get when we can expect that to happen. Would you be so kind as to give me any kind of estimation? We are using Deck 0.7.0 on Nextcloud 17 (stable). Thanks in advance!

**Comment by jakobroehrl** [comment]
> 
> Hi, we would love this collections/dashboard feature to go live for productive use. I don't quite get when we can expect that to happen. Would you be so kind as to give me any kind of estimation? We are using Deck 0.7.0 on Nextcloud 17 (stable). Thanks in advance!

@ardarandir 
We have to finish the vue migration first. There is no progress it the last weeks because of other priorities. Sorry, can't give a an estimation. Would love to see this feature, too :)

**Comment by juliushaertl** [comment]
In addition to the comments by @jancborchardt I think we should try to keep the main content view stay in a similar card based layout as the regular board view has. 

I don't see a good use case for an all cards view, as this would basically be just a long endless list without any proper filtering. We should aim to provide lists that give users a good overview or help them to find the relevant cards more easily.

### Due date view

Frame 5

The assigned to me list could also be grouped by duedates, as this is most likely what the priorization is done by. In addition we could allow users to apply custom filters on those lists with https://github.com/nextcloud/deck/issues/414

cc @nextcloud/designers

**Comment by juliushaertl** [comment]
Rebased and changed base branch to master

**Comment by alexanderdd** [comment]
Not sure how you resolve conflicting feedback around here?
Personally, I agree with https://github.com/nextcloud/deck/pull/1319#issuecomment-559928631 and while I think https://github.com/nextcloud/deck/pull/1319#issuecomment-577861069 has a good point, I think this should not stand in the way of merging this pull request.

Or is the only thing missing now the review (one post above)?

Thanks.

**Comment by juliushaertl** [comment]
> Or is the only thing missing now the "Review required"?

No, we definitely should address the mentioned points before merging. :wink:

**Comment by juliushaertl** [comment]
> Not sure how you resolve conflicting feedback around here?

Let's see if @jancborchardt and @nextcloud/designers have any comments on my additions.

**Comment by jancborchardt** [comment]
Agree with everything said by @juliushaertl in https://github.com/nextcloud/deck/pull/1319#issuecomment-577861069 :)

Only thing is that I’m not sure the list layout should use the card style, as that’s too many containers for a single-row layout. I tend towards doing it like @jakobroehrl above or as in the Tasks app.

cc @raimund-schluessler as this now gets very close into the same territory as Tasks and we should coordinate how best to move forward together. :) As @jakobroehrl mentioned, the other tools all go in the direction of just having views for the "to dos", instead of different apps: See Microsoft Tasks in Teams, Asana, Ticktick, Todoist, Ora, Zenkit, …

**Comment by raimund-schluessler** [comment]
> cc @raimund-schluessler as this now gets very close into the same territory as Tasks and we should coordinate how best to move forward together. :) As @jakobroehrl mentioned, the other tools all go in the direction of just having views for the "to dos", instead of different apps: See Microsoft Tasks in Teams, Asana, Ticktick, Todoist, Ora, Zenkit, …

The easiest would be if Deck would just use CalDAV 😉 Then the user could decide which view/app to use and re-implementing the same view for every app would not be necessary. A card view for the Tasks app was also requested once https://github.com/nextcloud/tasks/issues/100, but since we have Deck, that's not really reasonable.

However, exposing the Deck data as a CalDAV endpoint as described in https://github.com/nextcloud/deck/issues/15 by @juliushaertl wouldn't really do the trick. Tasks could then work with the Deck data, but Deck wouldn't be able to work with the Tasks data.

**Comment by juliushaertl** [comment]
> The easiest would be if Deck would just use CalDAV wink Then the user could decide which view/app to use and re-implementing the same view for every app would not be necessary. A card view for the Tasks app was also requested once nextcloud/tasks#100, but since we have Deck, that's not really reasonable.

> However, exposing the Deck data as a CalDAV endpoint as described in #15 by @juliushaertl wouldn't really do the trick. Tasks could then work with the Deck data, but Deck wouldn't be able to work with the Tasks data.

I also considered using CalDAV as a data source in the past, but this limits us somehow to represent the card data in the properties defined in the vevent/vtodo rfc. One big concern when discussing this with @georgehrke were tags and the actual stack a card is in. There is the category field which would work for tags, but then we don't have a way to represent the stack. Also the category is basically a free text field, so when changing a task over CalDAV there is no way in checking if such a stack actually exists on the board and if a card can be moved to that one. Other card data that might be hard to represent would be assigned users and attachments. 

I'm open for ideas on how we could solve this, as obviously having a shared data backend is what would make the most sense here, it's just that I don't see a proper way of achieving it.

**Comment by georgehrke** [comment]
Another big problem that would come up from taking CalDAV and `VTODO`s as a source for Deck would be how to handle recurring `VTODO`s. There is no concept of recurring cards in Deck.

I totally agree that from a Design POV, Deck should work on the same data as Tasks and just be an alternative view for it, but from a technical POV, this is introducing to many problems, which we have still no answers to.

**Comment by juliushaertl** [comment]
Back to the original topic of the pull request, I would suggest we go for a card based approach as well for now, as once boards are exposed as calendars with https://github.com/nextcloud/deck/pull/1545 we could redirect the user to the tasks app showing the cards in a list as a first starting point.

**Comment by BKapelari** [comment]
INFO: We did a quick transitional solution for our company by adding 3 widgets to the dashboard.
is not a really useful solution but it does the job. if you click on the link the card shows in detail view in deck.

Bildschirmfoto 2020-02-26 um 18 02 42

**Comment by jakobroehrl** [comment]
There are a lot of the same functionality in Deck and Tasks eg:
- assign to user
- share with user, group, circle
- comments
- attachments
- tags
- activity
- due dates
- filter, sort
- collections (dueToday, assignToMe, ...)

I think it's easier to interate a list/table view in Deck than duplicate and maintain the hole functionality in two apps.

**Comment by BKapelari** [comment]
> There are a lot of the same functionality in Deck and Tasks eg:
> 
>     * assign to user
> 
>     * share with user, group, circle
> 
>     * comments
> 
>     * attachments
> 
>     * tags
> 
>     * activity
> 
>     * due dates
> 
>     * filter, sort
> 
>     * collections (dueToday, assignToMe, ...)
> 
> 
> I think it's easier to interate a list/table view in Deck than duplicate and maintain the hole functionality in two apps.

how can you assing tasks to users in the Tasks App?

**Comment by jakobroehrl** [comment]
> 
> how can you assing tasks to users in the Tasks App?

You can't. But it's an function both tools should have.

**Comment by raimund-schluessler** [comment]
I continued our off-topic discussion in the correct issue: https://github.com/nextcloud/deck/issues/15#issuecomment-592582216

**Comment by alexanderdd** [comment]
So what will happen to this pull request? Merge or decline (if thats the right word)?

Path1
@juliushaertl proposed to use a card layout instead  https://github.com/nextcloud/deck/pull/1319#issuecomment-577861069

Path2
@jancborchardt said he likes the row style as proposed in this pull request, but some minor improvements are needed (these https://github.com/nextcloud/deck/pull/1319#issuecomment-577861069)

Which path will we continue? (I am never sure how decisions are made here...)

**Comment by juliushaertl** [comment]
> So what will happen to this pull request? Merge or decline (if thats the right word)?

Well, the discussion drove a bit into details that are actually part of #15 but are of course related to the lists. My comment from https://github.com/nextcloud/deck/pull/1319#issuecomment-591394936 still stands. So with that and the plan we came up with in https://github.com/nextcloud/deck/issues/15 I think reusing the tasks app for any list view would make the most sense here.

> Which path will we continue? (I am never sure how decisions are made here...)

We usually try to find a solution that is somehow common sense in the end. Let me quote our code of conduct here:

> Be pragmatic
> Nextcloud is a pragmatic community. We value tangible results over having the last word in a discussion. We defend our core values like freedom and respectful collaboration, but we don't let arguments about minor issues get in the way of achieving more important results. We are open to suggestions and welcome solutions regardless of their origin. When in doubt support a solution which helps getting things done over one which has theoretical merits, but isn't being worked on. Use the tools and methods which help getting the job done. Let decisions be taken by those who do the work.
https://nextcloud.com/contribute/code-of-conduct/

**Comment by juliushaertl** [comment]
I think we drifted away from what this pull request was actually about - the dashboard to give quick access to important cards.

Let me summarize what I think the consent was:
- Due dates - A column view makes most sense here as we can have the due date categorization as different columns here. 

- All cards - does not have a real use case -> Let's remove that one

## Open questions: 

### Assigned to me

>> Only thing is that I’m not sure the list layout should use the card style, as that’s too many containers for a single-row layout. I tend towards doing it like @jakobroehrl above or as in the Tasks app.

I was not arguing for a single row layout but to still provide some sort of grouping for the dashboard overview, like this:

> The assigned to me list could also be grouped by duedates, as this is most likely what the priorization is done by.

**Comment by juliushaertl** [comment]
Continued in https://github.com/nextcloud/deck/pull/1934

**Pull request closed without merging**
