### PR TITLE
feat: Enhance dark mode

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes https://github.com/nextcloud/deck/issues/5034

Screenshot 2023-08-30 at 16 44 14

Screenshot 2023-08-30 at 16 44 23

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by luka-nextcloud — CHANGES_REQUESTED** [review]
It looks awesome! From my point of view, there are 2 things that we need to address:
- lint and style lint issues
- for cards that are due in 1 day, they should not have overdue color
https://github.com/nextcloud/deck/pull/5045/files#diff-55bcb69bed8a7800314ac5edbaf095937c1500528731ef10faebb3e4cd8a7e85R76

**Comment by juliushaertl** [comment]
Thanks, good catch. Fixed.

**Review by luka-nextcloud — APPROVED** [review]

**Comment by juliushaertl** [comment]
Failure is unrelated

**Pull request merged**
