### PR TITLE
Add circles and groups to cards

### PR DESCRIPTION
**Pull request by jakobroehrl**
todo:
Add them to cards, too

### CODE REVIEW

**Comment by jakobroehrl** [comment]
@juliushaertl 
At the moment alle users from a board are shown in the Card Sidebar for sharing. They come from here:
https://github.com/nextcloud/deck/blob/vue/src/components/board/Board.vue#L92-L97

Should I add circles and groups to board.users on the BoardController?

**Comment by juliushaertl** [comment]
> Should I add circles and groups to board.users on the BoardController?

I just found that we still miss to add them in the backend. Once we fetch the list of circle members here https://github.com/nextcloud/deck/blob/29f6ae477bdc7f0530cb37d47033705587a8eb4b/lib/Service/PermissionService.php#L255 it should just work™

**Comment by juliushaertl** [comment]
> Should I add circles and groups to board.users on the BoardController?

I just found that we still miss to add them in the backend. Once we fetch the list of circle members here https://github.com/nextcloud/deck/blob/29f6ae477bdc7f0530cb37d47033705587a8eb4b/lib/Service/PermissionService.php#L255 it should just work™

**Comment by juliushaertl** [comment]
Anyway let's fix this in a separate PR.

**Pull request merged**
