### PR TITLE
Prepare 0.2 release

### PR DESCRIPTION
**Pull request by juliushaertl**
Please check if anything important is missing in the changelog. @artemanufrij @pixelipo 

I summarized the various styling fixes, hope that's ok for you.

- [x] Required before merging: #191
- [x] and #190 
- [x] New screenshots would be great

### CODE REVIEW

**Comment by artemanufrij** [comment]
Toggle navigation bar...

**Comment by artemanufrij** [comment]
PS: what do you think about a new screenshot... for app store?

**Comment by juliushaertl** [comment]
@artemanufrij Yes, new screenshot would be awesome :+1: Do you want to create one? :wink:

**Comment by pixelipo** [comment]
Looks good

**Pull request merged**
