### PR TITLE
Scroll board by dragging

### PR DESCRIPTION
**Pull request by juliushaertl**
* Resolves: #2480
* Target version: master 

Requires https://github.com/nextcloud/deck/pull/2230

- [ ] Make sure that only empty content area scrolls

### CODE REVIEW

**Comment by caiwan** [comment]
May I ask what about this PR? Will this feature included in a future version?

**Comment by shoetten** [comment]
After #4074 this should be much more intuitive. Do you want me to give this feature another go, @juliushaertl?

**Comment by juliushaertl** [comment]
@shoetten If you'd still up for that, any help would be much appreciated. Feel free to pick the commits from the branch or just create a new one. Also let me know if any questions arise.

**Comment by juliushaertl** [comment]
Let me close this as I currently don't have time to pick this up again, but as mentioned, contributions would be very welcome, so feel free to make use of the existing commits for submitting a new pull request.

**Pull request closed without merging**
