### PR TITLE
disables autocomplete on card creation

### PR DESCRIPTION
**Pull request by mokkin**
Signed-off-by: mokkin <mokkin@leipzig.freifunk.net>

* Resolves: https://github.com/nextcloud/deck/issues/4083
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by SchraderSarah** [comment]
Was this feature implemented in the latest update? I can't seem to find it.

**Pull request merged**
