### PR TITLE
Improve hovering response in board

### PR DESCRIPTION
**Pull request by simonspa**
Add "grab" cursor for stack titles.

I wanted to add the same for cards and a "grabbing" while moving, but I'm still fighting with scoped CSS.

Ref #1880

### CODE REVIEW

**Comment by simonspa** [comment]
Now also added slightly stronger drop shadow when hovering a card:

image

**Comment by simonspa** [comment]
@jancborchardt not sure if there is a unified way in NC design for this - but to me it looks unobstrusive but still improves user interaction.

**Comment by stefan-niedermann** [comment]
The border looks too dark. I wouldn't increase it but spread it wider instead.

**Comment by simonspa** [comment]
I played with that too, but I liked the darker border better. The problem with increasing the spread is that the rounding of the corners becomes very different from the card's corners - which then "pierce" through the shadow:

image


Also, in order to be noticeable enough the spread needs to be around 10px - which partially overlaps with adjacent elements already.

**Comment by juliushaertl** [comment]
I agree with @stefan-niedermann that the dark shadow looks a bit to strong, especially for a hover feedback. 

cc @Clementine46 @Nyco :wink: Maybe you have some input on that as well

**Comment by simonspa** [comment]
Okay, third option would be to combine a bit more `blur` with a smaller dark border as a way inbetween?

image

**Comment by juliushaertl** [comment]
Looks better to me :+1: 

For the overlapping issue with the header background I think it would be fine to decrease the height of the list header a bit and increase the spacing between header and first card so that the shadow is not cut anymore.

**Comment by simonspa** [comment]
Alright, did that - just increased the margin from 0 to 3px. Now looks like this:

image

**Comment by juliushaertl** [comment]
Let's get this in :+1:

**Comment by juliushaertl** [comment]
Frontend tests happy and no backend changes ... merging

**Pull request merged**
