### PR TITLE
feat: #2906 add card ID badge

### PR DESCRIPTION
**Pull request by oneWaveAdrian**
- adds vscode settings file to gitingore
- adds new badge for card ID
- adds card ID to board filter
- adds settings to disable card ID badge

* Resolves: #2906 
* Target version: master 

### Summary
Adds ID Badge to top left corner of card.
image

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by ultrasites — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]

**Comment by ultrasites** [comment]
In which version this feature will be included?

**Comment by juliushaertl** [comment]
This has been merged for the next feature release which is bound to Nextcloud 26. Currently scheduled for mid March according to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by ultrasites** [comment]
@juliushaertl is it included now? I can't find it in the release notes for Nextcloud 26, Deck v. 1.9.0

**Comment by ultrasites** [comment]
@juliushaertl  reminder?

**Comment by juliushaertl** [comment]
Not sure why it is missing in the changelog but yes, it has been released with 1.9.0 (starting with beta.1 to be exact)

**Comment by ultrasites** [comment]
Wow, thx for your very fast answer!

**Pull request merged**
