### PR TITLE
Switch to 'markdown-it-task-checkbox' for rendering of task lists

### PR DESCRIPTION
**Pull request by q-wertz**
Signed-off-by: q-wertz <clemens.sonnleitner@web.de>

* Resolves: #2109 
* Target version: master 

### Summary
As suggested by [@https://github.com/hrk](https://github.com/nextcloud/deck/issues/2109#issuecomment-657190716) I gave it a shot and tried to use the library `markdown-it-task-checkbox` instead of `markdown-it-task-lists`.

- Not sure if some of the features that were added to `markdown-it-task-lists` are needed. I tried to get the same classnames for `ulClass` and `liClass` but e.g. the `enabled` class to the `<li>` elements (which has been introduced with v2.0.0 of `markdown-it-task-lists`) cannot be set (but did not find any references in the Deck app which seem to require this).
- Also not sure whether PR https://github.com/nextcloud/deck/pull/3833 has any side effects on this.

### TODO

- [ ] Double check code validity (I'm neither an experienced web developer nor do I have deep insights in Deck or Nextcloud) 
- [ ] Test

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included -> Don't think additional specific tests are required
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Tested and works and the library also seem sane to use, thanks a lot for this 👍

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Can you maybe also push the package-lock.json updates after running `npm install --save markdown-it-task-checkbox` While I could rebase through the web UI it seems I cannot push from my local machine to your branch.

**Comment by q-wertz** [comment]
Is this also backported to NC 23?

**Comment by q-wertz** [comment]
Is there any information when this will be in any stable version? :sweat_smile:

**Pull request merged**
