### PR TITLE
Bump bower dependencies

### PR DESCRIPTION
**Pull request by juliushaertl**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

We can upgrade ng-sortable again since https://github.com/a5hik/ng-sortable/issues/365 is fixed with 1.3.8.

### CODE REVIEW

**Comment by juliushaertl** [comment]
@artemanufrij Running `make install-deps` should make sure that bower downloads the new versions.

**Comment by artemanufrij** [comment]
@juliushaertl ok. that works. but now I have 14k files. How can I make a "build"?

**Comment by juliushaertl** [comment]
@artemanufrij `make appstore` will generate a .tar.gz file that you can deploy to your Nextcloud instance and doesn't include build dependencies. When running the app directly from git in your nextcloud you just need `make build` but then you will still have all node dependencies.

**Comment by artemanufrij** [comment]
@juliushaertl 
1. `make install-deps` -> ok!
2. `make appstore` ->ok!
copy content of the `dock.tar.gz` file into fresh nextcloud instance 11.0.3
--> same failure `{{ b.title }}`

**Comment by artemanufrij** [comment]
Works as expected

**Pull request merged**
