### PR TITLE
changed space between cards

### PR DESCRIPTION
**Pull request by artemanufrij**
Signed-off-by: Artem Anufrij <artem.anufrij@live.de>

### CODE REVIEW

**Comment by artemanufrij** [comment]
**before:**
cards_before

**after:**
cards_after

**Comment by juliushaertl** [comment]
@artemanufrij Yes that looks better than before. :+1:

**Comment by pixelipo** [comment]
I'm not so sure that we need that much space between cards - it will result in one card less per screen every 7 cards...

**Comment by pixelipo** [comment]
Merged without review, @juliushaertl ?

**Comment by juliushaertl** [comment]
Was counting my :+1: as review :wink: 

But I also recogniced that on decks with many cards this is quite much unused space that would be better used if we show more cards. Maybe we should revert this. :see_no_evil:

**Comment by artemanufrij** [comment]
@juliushaertl @pixelipo what do you talk about :smiley_cat: ? At home 21:9 34" at work: 4k :smile:

**Pull request merged**
