### PR TITLE
Add SPDX header

### PR DESCRIPTION
**Pull request by AndyScherzinger**
* Resolves: none
* Target version: main

### Summary

* Add SPDX headers, replacing existing ones
* Add REUSE action to check future PRs for compliance
* Replaced most icons with current material ones and ran them through an optimizer to reduce size

### TODO

- [ ] Test svg rendering, especially on iOS devices while https://github.com/nextcloud/deck/pull/5825/commits/2777a0b8dbff597ac80166c73bdde36ee58f0220 should have this covered

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
Also CC @jancborchardt given the replacement of most icons now using latest material design icons

**Review by jancborchardt — APPROVED** [review]
Looks good to me!

**Comment by AndyScherzinger** [comment]
@juliushaertl any pointers why the tests fail? https://github.com/nextcloud/deck/actions/runs/8986613630/job/24683151834?pr=5825 (and how I could fix them?)

**Comment by juliushaertl** [comment]
Its an unrelated failure also on main since a week, I already spent some time trying to figure this out, but haven't made much progress so far. Will do a quick test run locally, but as code hasn't changed this seems good to get in

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Passing locally, thanks a lot @AndyScherzinger 💙

**Comment by AndyScherzinger** [comment]
Happy to help 😊

**Pull request merged**
