### PR TITLE
Hide comments tab if comments app is disabled

### PR DESCRIPTION
**Pull request by juliushaertl**
Signed-off-by: Julius Härtl <jus@bitgrid.net>

* Resolves: # 
* Target version: master 

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Hey @juliushaertl

i guess also 3rd party clients should also check this and hide the comments as well?

But how can one check this? A quick look at the `capabilities`-endpoint ([sample](https://github.com/stefan-niedermann/nextcloud-deck/issues/317#issuecomment-610926466)) did not reveal any "comments"-app...?

**Comment by juliushaertl** [comment]
Maybe @tobiasKaminsky can help here as that should also be done on the files app. Is there something like that already?

**Comment by tobiasKaminsky** [comment]
I think comments are a core feature and cannot be disabled, @blizzz

**Comment by juliushaertl** [comment]
At least `occ app:disable comments` works

**Comment by tobiasKaminsky** [comment]
https://github.com/nextcloud/server/issues/20612

**Comment by stefan-niedermann** [comment]
Thank you @tobiasKaminsky 

We will track this in nextcloud/server#20612 and https://github.com/stefan-niedermann/nextcloud-deck/issues/401

**Comment by blizzz** [comment]
> At least `occ app:disable comments` works

Technically, it just hides the UI. The functionality itself is still there. The comments service and model are both in the server, and the API is implement in DAV, which you cannot disable.

**Pull request merged**
