### PR TITLE
Moved "Add a new Stack" into the top Bar

### PR DESCRIPTION
**Pull request by artemanufrij**
#91 #89
Moved "Add a new Stack" into the top Bar

### CODE REVIEW

**Comment by artemanufrij** [comment]
screenshot_20170425_154428

**Comment by artemanufrij** [comment]
Wie kann ich diesen Branch nachträglich signieren?
in meinem Fall:
 Signed-off-by: Artem Anufrij <artem.anufrij@live.de>

**Comment by juliushaertl** [comment]
@artemanufrij Thanks for your contribution. :tada: 

Looks definitely more consistent to the overall Nextcloud UI. I'll have a more detailed look at the code tomorrow. 

You can squash those commits into one and then just signoff this single commit using 
`git commit --amend --signoff`

**Comment by artemanufrij** [comment]
@juliushaertl Thank you for your support!

**Comment by juliushaertl** [comment]
Changes look good so far, except for some positioning issues:

Chrome:
2017-04-26-144741_425x146_scrot

Firefox:
2017-04-26-144917_367x118_scrot

Can you fix those as well? Thanks so far :+1:

**Comment by artemanufrij** [comment]
@juliushaertl sure...

**Comment by artemanufrij** [comment]
@juliushaertl done:
screenshot_20170426_224749

**Comment by juliushaertl** [comment]
Closed in favour of #95

**Pull request closed without merging**
