### PR TITLE
Gracefully handle not found card for a share

### PR DESCRIPTION
**Pull request by mejo-**
Fixes: #3464
Fixes: #4565

* Resolves: # 
* Target version: main

### CODE REVIEW

**Comment by mejo-** [comment]
> shouldn't a share to a non existing card be deleted and not ignored?

We should rather make sure that shares get deleted along with the cards, but that's a separate topic. Also, since cards don't get deleted straight away but only get marked as deleted, we'd have to clean up shares in the cronjob that actually deletes the cards.

**Comment by mejo-** [comment]
@juliushaertl the PR is tested and ready for review now.

**Comment by juliushaertl** [comment]
Still curious how this could happen as the DeleteCron should also drop the share through the attachment implementation https://github.com/nextcloud/deck/blob/1f66c66ad3a5e830c17a7f2fc43f0ec6901d492b/lib/Service/FilesAppService.php#L276 Any idea about that from your investigations @mejo- ?

Nevertheless the change makes sense

**Review by juliushaertl — APPROVED** [review]

**Comment by mejo-** [comment]
>  Any idea about that from your investigations @mejo- ?

Yep. Whenever you soft-delete a card, it will no longer be found by `cardMapper->find()`, resulting in this error. So any soft-deleted card that has an attachment shared with it led to this bug in my understanding. Probably the problem got solved by `DeleteCron` when it really deleted the card and its related attachments.

**Pull request merged**
