### PR TITLE
added a card control bar

### PR DESCRIPTION
**Pull request by artemanufrij**
Signed-off-by: Artem Anufrij <artem.anufrij@live.de>

### CODE REVIEW

**Comment by artemanufrij** [comment]
fixed #138 #131

**Comment by artemanufrij** [comment]
screenshot_20170519_121050

**Comment by juliushaertl** [comment]
I like it, but there is really much space lost when there is no icon displayed:

2017-05-19-171830_342x92_scrot

**Comment by artemanufrij** [comment]
@juliushaerl we will have an attachment, date icons etc. the future.

**Pull request merged**
