### PR TITLE
Cache user membership for circles

### PR DESCRIPTION
**Pull request by juliushaertl**
Saves one relatively large query for each attachment of a deck card if shared with a circle:

```
select ... from oc_circles_circle cc left join oc_circles_member cc_wn on (cc_wn.circle_id = cc.unique_id) and (cc_wn.level = ?) left join oc_circles_membership cc_ms on (cc_ms.single_id = ?) and (cc_ms.circle_id = cc.unique_id) left join oc_circles_member cc_di on (cc_di.single_id = ?) and (cc_di.circle_id = cc.unique_id) left join oc_circles_circle cc_wn_on on cc_wn_on.unique_id = cc_wn.single_id left join oc_circles_circle cc_ms_cf on (cc_ms.circle_id = cc_ms_cf.unique_id) or (cc_di.circle_id = cc_ms_cf.unique_id) left join oc_circles_member cc_in on (cc_ms.inheritance_first = cc_in.single_id) and (cc_ms.circle_id = cc_in.circle_id) left join oc_circles_member cc_in_by on (cc_ms.single_id = cc_in_by.single_id) and (cc_ms.inheritance_last = cc_in_by.circle_id) left join oc_circles_circle cc_in_on on cc_in_on.unique_id = cc_in.single_id where (cc.unique_id = ?) and ((?) = ?) and ((((?) > ?) and (cc_ms.level = ?)) or (((cc_ms.level >= ?) or (cc_di.level >= ?)) and ((?) = ?)) or ((?) > ?))
```

As we check if the current user is member of the circle for each share mountpoint this brings quite some improvement in the (partial) file system setup when loading deck mounts.

Comparison with 22 attachments on one card shared with one circle for the recipient user:

Screenshot 2022-09-21 at 13 49 01
Screenshot 2022-09-21 at 13 50 10

### CODE REVIEW

**Comment by juliushaertl** [comment]
cc @ArtificialOwl Maybe it would also make sense to introduce some caching directly in the CirclesManager so that not every call hits the db :)

**Comment by ArtificialOwl** [comment]
https://github.com/nextcloud/circles/pull/1155

**Pull request merged**
