### PR TITLE
Fix assigning newly created labels

### LINKED ISSUE #252: Labels sometimes don’t get saved
### Steps to reproduce
1. Create a card
2. Add a label to it
3. Sometimes it vanishes

Either directly after closing the sidebar, or for example after adding a date, or removing a date again. Not entirely sure why that is.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/47119298-labels-sometimes-don-t-get-saved?utm_campaign=plugin&utm_content=tracker%2F52758431&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52758431&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by juliushaertl**
fixes #252

Steps to reproduce:
- create a new label
- assign it to a card
- reload the page

Signed-off-by: Julius Härtl <jus@bitgrid.net>

### CODE REVIEW

**Comment by jancborchardt** [comment]
@9662 @rallek can you also review since it fixes a bug you reported? :)

(@juliushaertl always @-mention the people who were active in an issue to review, that can speed things up and involve more community folks. ;)

**Comment by juliushaertl** [comment]
@jancborchardt Yeah makes sense ;) sometimes I forget to check back to the issue

**Comment by MorrisJobke** [comment]
@juliushaertl Backport or not backport? Otherwise drop the label :P

**Comment by juliushaertl** [comment]
backported to stable0.3 with cae999ec80c7c96e1bb6a497befb678a95aa7c8d

**Pull request merged**
