### PR TITLE
Fix numeric types and missing card id in card detail results

### LINKED ISSUE #771: API/JSON incosistencies
Hi @juliushaertl 
This is rather a question/discussion, can really say if it is to be considered a feature, a bug orr to be ignored.

Please see below the actual (0.5.1) JSON element for a card retrieved in the Android client, see https://github.com/stefan-niedermann/nextcloud-deck/pull/16#issuecomment-445237500
```
{
"title":"Fix some naughty bug",
"description":"getRandom always returns four\nThis is line two\nThis is line three",
"stackId":8,
"type":"plain",
"lastModified":1544169560,
"lastEditor":"andy",
"createdAt":1544169433,
"labels":[
{"title":"To review","color":"317CCC","boardId":"5","cardId":null,"id":18},
{"title":"Later","color":"F1DB50","boardId":"5","cardId":null,"id":20}
],
"assignedUsers":[
{"id":2,"participant":{"primaryKey":"andy","uid":"andy","displayname":"Andy"},"cardId":"24"}
],
"attachments":null,
"attachmentCount":0,
"owner":"andy",
"order":999,
"archived":false,
"duedate":"2018-12-14T07:59:20+00:00",
"deletedAt":0,
"commentsUnread":0,
"id":24,
"overdue":0
}
```
* the label/```cardId``` of the labels is always `null` and  #774 
* the label/`boardId` is a `String` instead of a `long` #774 
* the assignedUser/```cardId``` of the assignedUsers is is a `String` instead of a `long` #774 
* `lastModified`, `createdAt` and `duedate` are all dates/timestamps while being mixed types long/date-string where the date string ships the timezone (kudos for that!) #809 

Any feedback is highly appreciated, as always :) ❤️ 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/67180225-api-json-incosistencies?utm_campaign=plugin&utm_content=tracker%2F52758431&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52758431&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by juliushaertl**
Fixes #771

### CODE REVIEW

**Comment by juliushaertl** [comment]
@AndyScherzinger @desperateCoder I've bundled a test release with the fixes https://cloud.nextcloud.com/s/dSmqmFcXp79kWMR Mind to give it a try?

**Comment by desperateCoder** [comment]
Hi @juliushaertl ,

i wasn't able to test it, but i got a new Inconsitency:

Sometimes the owner of a Card looks like this:
``` json
"owner":"artur"
```
but sometimes i get this:
``` json
"owner":{
      "primaryKey":"artur",
      "uid":"artur",
      "displayname":"artur"
}
```
this makes it pretty hard to know, how i have to parse it... can we somehow fix that, too?

**Comment by AndyScherzinger** [comment]
@juliushaertl how do I have to install it?

**Comment by juliushaertl** [comment]
> @juliushaertl how do I have to install it?

You can just extract it, remove the old deck folder in your Nextcloud installation and replace it with the new one. 

> this makes it pretty hard to know, how i have to parse it... can we somehow fix that, too?

Yes, it is just extended information sometimes, because we don't need it at every point in the frontend, iirc. But I'll look into always providing that details.

**Comment by desperateCoder** [comment]
If this information isn't relevant, I'd expect it to be omitted completely. This would be no problem at all, since I still get the information in the card-details-call.

**Comment by juliushaertl** [comment]
Let's get this in as a first fix for the numeric types.

**Pull request merged**
