### PR TITLE
Fix deleting boards and add a simple undo function

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix for #108 and #85 for boards only

Please test @himbeere @artemanufrij

### CODE REVIEW

**Comment by artemanufrij** [comment]
@juliushaertl will do it when I back home :)

**Comment by artemanufrij** [comment]
@juliushaertl Can't test it. look here:
screenshot_20170502_201746

**Comment by artemanufrij** [comment]
@juliushaertl 
Deleting works as expected for me... And I can stop it...

* it's not possible to delete board instand... I have to wait for the time...

* It's not really clear that you can cancel it by clicking timer label --> maybe a "stop" or "X" button...

**Comment by juliushaertl** [comment]
@artemanufrij Good point, I'll add a Stop text when hovering maybe.

**Comment by juliushaertl** [comment]
Let's merge, since it fixes #108.

**Pull request merged**
