### PR TITLE
Do not open the dialog automatically upon card creation, only upon click

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix modal design issues as proposed in #2423

### CODE REVIEW

**Review by ma12-co — COMMENTED** [review]
@juliushaertl I wouldn't open the sidebar either upon card creation, what do you think?

**Comment by ma12-co** [comment]
Actually, @juliushaertl, the sidebar should probably never overlap the content, just like in talk

**Comment by juliushaertl** [comment]
> Actually, @juliushaertl, the sidebar should probably never overlap the content, just like in talk

It doesn't, the scroll container is reduced to the remaining width. That is a bit special for deck of course, but there is no way around horizontal scrolling here.

**Comment by ma12-co** [comment]
So this is the problem I'm thinking of here: 

Peek 2020-10-13 10-35

**Comment by juliushaertl** [comment]
Ok, there it might help already if we scroll the cards into view after inserting them with #2230

**Review by ma12-co — APPROVED** [review]

**Pull request merged**
