### PR TITLE
reduce card spacing

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>
* Target version: master 

**Before**
grafik

**After**
grafik

### CODE REVIEW

**Comment by juliushaertl** [comment]
I think the spacing actually helps here to distinguish the individual tasks, maybe we can just reduce the space if we are in compact mode?

**Comment by bpcurse** [comment]
> I think the spacing actually helps here to distinguish the individual tasks, maybe we can just reduce the space if we are in compact mode?

I wanted to propose this spacing reduction for a long time myself, but somehow always forgot about it.
Of course spacing is needed to distinguish individual tasks, but the actual spacing is a bit too large. This helps a little to better use the available space.

**Comment by jakobroehrl** [comment]
I would discuss about reducing the space even more. 
Here some shots, there is a lot less space:

grafik
grafik
grafik

@jancborchardt 
What are you thinking about this? I personal like it to see more content and have less space

**Comment by juliushaertl** [comment]
Thinking about this a bit more ... actually I changed my mind a bit :see_no_evil: I've pushed another commit to fix the small offset on the left/right.

**Pull request merged**
