### PR TITLE
Limit stack/card title overflow - fixes #131

### LINKED ISSUE #131: Card title overflows/goes under the card-options button
See screenshot for two (related) problems:

title-overflow

It's really simple to fix - I'll create a PR tomorrow

### PR DESCRIPTION
**Pull request by pixelipo**
Additionaly, this fixes positioning of the action buttons (always in top right corner) as well as an HTML validity issue (`<div>` inside an `<h2>`)

Signed-off-by: Marin Treselj <marin@pixelipo.com>

### CODE REVIEW

**Comment by artemanufrij** [comment]
we should use 100% space for card title
screenshot_20170519_130605

**Comment by artemanufrij** [comment]
@pixelipo check pls #139. I think it fixes that issue

**Comment by pixelipo** [comment]
@artemanufrij #139 doesn't fix the stack title issue.

**Comment by artemanufrij** [comment]
@pixelipo you are right. this is for stack issue #137

**Comment by juliushaertl** [comment]
@pixelipo This is now integrated in the other PR, right?

**Comment by pixelipo** [comment]
I think neither this nor #139 are perfect solutions.

I've been thinking about this problem a bit, and it seems that we are trying to fit stuff onto a card that shouldn't really belong there. 

Archive and Delete are **actions**. They are not even the most common actions a user performs on a card - I would argue those are "Edit (title)" and "Add description". So why are they even present in card view? Why don't we move them over to the modal sidebar?
Attachment, Date, Labels, Description indicator are **content**.

So the idea is that card only displays content, while sidebar is used for editing cards (title, labels, description, attachments, due date, archive, delete). What say you, @artemanufrij @juliushaertl ?

If we take that route, it would be good to plan the space for all the possible content indicators that we might want to place on the card, even if we still don't have those functions ready.

**Pull request closed without merging**
