### PR TITLE
Feature/undo delete cards and stacks

### LINKED ISSUE #259: Add undelete to stack [$10]
Adding undelete to stack or at least a verification if the person is sure to delete a stack. happened to my org. that someone accidentally deleted a stack and it's too bad there's no way of getting it back or at least have a prompter to verify it.

Keep up the great work on the Deck. it's amazing!

<bountysource-plugin>

---
There is a **[$10 open bounty](https://www.bountysource.com/issues/47252786-add-undelete-to-stack?utm_campaign=plugin&utm_content=tracker%2F52758431&utm_medium=issues&utm_source=github)** on this issue. Add to the bounty at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52758431&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LemonAndroid**
Closes #259

### CODE REVIEW

**Comment by LemonAndroid** [comment]
@juliushaertl 

The drone ci is still failing with the branch pulled into the repo.

**Comment by LemonAndroid** [comment]
@juliushaertl 
Is there a helper for relative time?

**Comment by juliushaertl** [comment]
@LemonAndroid I took the liberty to rebase the branch to current master. Tests run fine now, except for the failures. 

It would be awesome if you could go though the commits and add a sign-off message, so that the CI is happy. :wink: I have written down some instructions on how to do that here: https://github.com/nextcloud/deck/pull/512#issuecomment-401524649 You basically just need to change the HEAD~2 to match the proper base commit of the branch.

> Is there a helper for relative time?

There are some angular filters for this: https://github.com/nextcloud/deck/blob/24f4f84eb68112ffad87a39851f4470241a2e2e1/js/filters/dateFilters.js#L28

**Comment by juliushaertl** [comment]
@LemonAndroid Please also have a look at https://app.codacy.com/app/juliushaertl/deck/pullRequest?prid=1963741

**Comment by LemonAndroid** [comment]
@juliushaertl So it would be ok to squash all commits into one and sign that one off? That'd be my preferred option.

**Comment by LemonAndroid** [comment]
@juliushaertl Why do the travis tests pass but the dron tests do not?

**Comment by LemonAndroid** [comment]
@juliushaertl Should codacy not complain now, I consider this done now.

**Comment by juliushaertl** [comment]
Great work @LemonAndroid Thank you very much for this enhancement.

**Pull request merged**
