### PR TITLE
Permanently delete deck cards marked as deleted after 5 min in a cron job

### LINKED ISSUE #2927: Deleted deck cards are being kept in deleted items forever
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the bug**

**To Reproduce**
1. Go to a board
2. Click on deleted items
3. Scroll down to the bottom of the list
4. See that the earliest cards are still sitting in deleted, and haven't been cleaned up. This includes any attachments which remain on the file system

**Expected behavior**
For there to only be deleted items from a short period leading up.

**Screenshots**
image

**Client details:**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 20.0.8

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

</details>

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

### PR DESCRIPTION
**Pull request by juliushaertl**
Replaces https://github.com/nextcloud/deck/pull/3279

Fixes #2927

### CODE REVIEW

**Comment by juliushaertl** [comment]
Behat failures are unrelated, fix is in https://github.com/nextcloud/deck/pull/4184

**Comment by Stachelritter** [comment]
Would it be possible to do a backport and release on stable25, or will this fix only be available with version 26?

**Comment by Stachelritter** [comment]
Would it be possible to do a backport and release on stable25, or will this fix only be available with version 26 of Nextcloud? @juliushaertl

**Comment by juliushaertl** [comment]
Yes, lets backport that 👍

**Comment by 31337-4554551n** [comment]
I believe this would be the right place to mention this, but I'm seeing everything related to deck cards auto deleting when deleted being marked as merged/closed/complete, but the issue persists.

Deleted deck cards still remain forever. NC 25.
-can't seem to attach screenshot, but items are still in deleted items forever-newly created/deleted ones also don't autodelete

**Pull request merged**
