### PR TITLE
allow user to toggle visibility of the calendar for a deck board

### PR DESCRIPTION
**Pull request by schiessle**
* Resolves:  https://github.com/nextcloud/deck/issues/4618

* Target version: main

### Summary

The calendar object needs to be exposed with "write-properties" in order to allow users to hide/show the corresponding calendar in the calendar app. It doesn't has any affects on the general permissions for the whole board or the individual cards. As soon as you select a calendar item you jump to the deck app where the normal deck permissions are applied.

As far as I understand it, caldav knows two kind if write permissions:

* "{DAV:}write" for editing calendar entries
* "{DAV:}write-properties" to only edit properties (like the visibility) of the calendar.

Looking at how we treat shared regular calendars, I think the solution should be fine: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Calendar.php#L181

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

@juliushaertl This was a quick try to fix a issue I discovered, does it makes sense?

### CODE REVIEW

**Comment by schiessle** [comment]
@juliushaertl I added the additional checks.

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Tested and works. I quickly fixed the php code style error.

**Comment by juliushaertl** [comment]
DCO check seems confused

**Pull request merged**
