### PR TITLE
Unified search implementation

### PR DESCRIPTION
**Pull request by juliushaertl**

### CODE REVIEW

**Comment by jakobroehrl** [comment]
Doesn't work for me:
Got this error: "Call to undefined method OCA\\Deck\\Search\\DeckProvider::getUserBoards()"

grafik

**Comment by juliushaertl** [comment]
Pushed a fix for that.

**Comment by juliushaertl** [comment]
> Card comments aren't searched

Let's do this in a follow-up as it it less urgent imo. Implementation can be based on https://github.com/juliushaertl/server/blob/2c699e090179a2ca235d28540b5999e27c36b9de/apps/comments/lib/Search/LegacyProvider.php#L66 and https://github.com/nextcloud/server/blob/ea8f68bea6957ae459ff1ba6849b25354b3f0093/apps/comments/lib/Search/CommentsSearchProvider.php

**Comment by juliushaertl** [comment]
Missing pieces for a follow up:
- [ ] Pagination for search results
- [ ] Search comments

**Review by jakobroehrl — APPROVED** [review]
This thing is working!

**Pull request merged**
