### PR TITLE
fix: open card with direct link

### PR DESCRIPTION
**Pull request by luka-nextcloud**
* Resolves: #5086
* Target version: main

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by luka-nextcloud** [comment]
@max-nextcloud Could you please review? Thanks.

**Comment by juliushaertl** [comment]
@luka-nextcloud I fail to reproduce the issue this is supposed to fix. I would expect the previous code to already work as expected. Can you tell if you can still see this issue on the main branch and maybe provide some detailed steps you take to reproduce?

**Comment by juliushaertl** [comment]
Maybe it is just something on stable27/stable26 ...

**Comment by luka-nextcloud** [comment]
> Maybe it is just something on stable27/stable26 ...

I've tested on them, I cannot reproduce.

**Comment by juliushaertl** [comment]
Let's close this then for now. We can reconsider the fix if we manage to reproduce or run into this again somehow.

**Pull request closed without merging**
