### PR TITLE
Delete file shares through attachments API

### PR DESCRIPTION
**Pull request by juliushaertl**
Previously the file was deleted in the file structure of the user is not
expected as the file might not only be related to the card.

Fixes https://github.com/nextcloud/deck/issues/2877

### CODE REVIEW

**Review by eneiluj — COMMENTED** [review]
I don't know exactly all that what is changed by this PR.

Did some tests though:
* Before: Removing an attachment (local or directly uploaded) deletes the file
* With this PR, removing an attachment does not delete the file
* Another scenario with this PR:
    * User A share a file F with user B (user share via Files)
    * User A shares a board with user B
    * User A adds file F as attachment to a card, file is shared with the card
    * User B leaves the user share related with file F
    * User B sees file F as attachment of the card but as a "pending share"

So it seems fine to me. Is there any other use case to check?

**Comment by juliushaertl** [comment]
No the first case was what this PR was supposed to cover. Before still had the approach from the old attachments where the file would be deleted which doesn't fit the model with sharing a file from the files app anymore.

**Pull request merged**
