### PR TITLE
IE11 fixes

### LINKED ISSUE #265: IE11 angularJS bugs (I have patched already, the solution is inside)
Sorry for the "unusual" way of this post, but PLEASE juste make **style** like this (for example in part.board.mainwiew.php). it will take you 5 mins to patch all files....

ng-style="{ 'background-color' : '#{{boardservice.getCurrent().color}}' , 'color' : '#{{boardservice.getCurrent().color | textColorFilter}}' }"

INSTEAD OF

style="background-color: #{{boardservice.getCurrent().color }}; color: {{boardservice.getCurrent().color | textColorFilter }};"

ACCORDING TO [AngularJS Doc](https://docs.angularjs.org/guide/ie)

A lot of people are still using IE11 onto Win7...

### PR DESCRIPTION
**Pull request by jacestk**
Fixes #265

### CODE REVIEW

**Comment by jacestk** [comment]
how can I deleted the first commit (which is completly nasty)

**Comment by juliushaertl** [comment]
@jacestk You can do that with an interactive rebase. Run `git rebase -i HEAD~2` on the command line and just delete the commit that you want to remove from the editor then.

**Comment by jacestk** [comment]
Now way without using git command line?

**Comment by pixelipo** [comment]
@jacestk without git CLI only if you scrap this completely and create a brand new branch and PR from master

**Comment by juliushaertl** [comment]
@jacestk I guess there is a way in some git gui clients, but I have no idea on how to use any of those.

**Comment by juliushaertl** [comment]
@jacestk I created a new PR with your commit to fix this, so we can get this merged for the next bugfix release.

**Pull request closed without merging**
