### PR TITLE
Merge pull request #1434 from 4workers/insensitive-search

### PR DESCRIPTION
**Pull request by matchish**
* Resolves: https://github.com/nextcloud/deck/issues/1233
* Target version: master

### CODE REVIEW

**Comment by juliushaertl** [comment]
> Found non-literal argument to RegExp Constructor

Can be ignored since we are running this in the frontend so the user would just be able to trigger a DoS on their own browser tab.

**Comment by matchish** [comment]
> > Found non-literal argument to RegExp Constructor
> 
> Can be ignored since we are running this in the frontend so the user would just be able to trigger a DoS on their own browser tab.

Could you tell me the rule name? I can't find the rule name to ignore the error.

**Comment by matchish** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
That should be the correct rule, but I'm not sure how codacy is checking that. Fine to merge from my side and dismis the warning in codacy. Also our own eslint run is fine: https://drone.nextcloud.com/nextcloud/deck/2714/5/2

**Comment by juliushaertl** [comment]
Thanks a lot for the contribution :rocket:

**Pull request merged**
