### PR TITLE
add board categories

### PR DESCRIPTION
**Pull request by weeman1337**
* Resolves: #2006
* Target version: master 

### Summary

Adds board categories

- Uncategorised boards are will be displayed under "Uncategorised"
- If there are no categories the section will be named "All boards" as before
- Archived boards will be displayed under "Archived"
- Board categegories can be set in a new section in the board details

image

### TODO

- [ ] The settings icon has a wrong colour. Is there any icon I can use?
- [ ] "Approval" of the category selection field in the sidebar (I had no idea where else to put it)

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
@weeman1337 as an API consumer i wonder how those new properties are exposed at and can be set with the Rest API?

Maybe you can add some documentation regarding this topic? 🙂 

cc @desperateCoder

**Comment by desperateCoder** [comment]
Please allow me to add my two cents:

As I can see in the migration script, you plan exactly one category per board. Are you sure you want to have a hard time extending it once as customers need more than one?

Also, this leads to redundancy and has an impact on performance, even if its indexed. Please consider a separate table with an n:m relation table.

**Comment by weeman1337** [comment]
> As I can see in the migration script, you plan exactly one category per board. Are you sure you want to have a hard time extending it once as customers need more than one?

If that happens at one day in the future - isn't it just another migration then? It should be one category per board keeping things simple.

> Also, this leads to redundancy and has an impact on performance, even if its indexed. Please consider a separate table with an n:m relation table.

I am fine with the db normalisation :+1: Will do that later.  
The n:m relation looks kind of over-engineered to me when not using it.

**Comment by desperateCoder** [comment]
Thanks for considering!

I read "category" and was like expecting, that a board can have more than one, otherwise the wording would have been something like "folder" or something. I guess I'm wrong here.

Regarding migrations: extracting the categories into a dedicated table will make things much easier, so I'm totally fine with your suggested solution. I just thought it isn't that much of an additional effort to make the relationship n:m and I know users very well. They'll complain and I'll then have to send them right back to you (I'm the co-maintainer of the android deck app). 

Since migration in Android (and in general) is pure pain, I'm happy that you are at least willing to extract the categories, so: thanks! 😅

**Comment by weeman1337** [comment]
> I read "category" and was like expecting, that a board can have more than one, otherwise the wording would have been something like "folder" or something. I guess I'm wrong here.

Regarding this point I may to refer to this https://github.com/nextcloud/deck/issues/2006#issuecomment-897036541 There has been more than a month time to give feedback on it. Getting feedback before starting the work helps keeping the motivation high and doesn't waste time :)

> Since migration in Android (and in general) is pure pain, I'm happy that you are at least willing to extract the categories, so: thanks!

I will update the DB structure because normalisation is a valid point. On the other hand I don't expect so many boards that this field may become a real problem or performance issue. Extracting it increases complexity. For example the relation has to be kept. Maybe this will be a tie performance wise :shrug: 

Anyway I am not planning to adapt the API to keep categories separated. This would make it much more complex.

**Comment by desperateCoder** [comment]
> Getting feedback before starting the work helps keeping the motivation high and doesn't waste time :)

Totally agree! I was mentioned here and just threw my two cents in. @stefan-niedermann is the one keeping up with you guys, I'm kind of the coding monkey here. Didn't know there was a previous discussion on that, sorry.

> On the other hand I don't expect so many boards that this field may become a real problem or performance issue

Nextcloud GmbH is kind of proud of their scalability, so I thought that was a thing here. You're right in 99% of the cases, and I understand that.  Don't take me too serious, it's mostly that I just have done it differently, but since you're the one contributing, who am I to complain? Thanks for your contribution!

**Comment by nimishavijay** [comment]
Agreed, it completely depends on the use case.

If it is called a category then I would expect a board would belong to only one category. Eg. Under category `Personal` there would be boards `Daily tasks`, `Personal project`. Under category `Work` there would be boards `Bug fixes`, `Marketing`.
Categories would be a way of grouping boards.

If a board belongs to multiple categories, then I would associate that with tags and groups more than folders or categories. For example a board `Personal website` could be tagged with `2021`, `college applications`, `personal`. 

It really depends on the use case, but I am leaning towards 1 category per board for simplicity and familiarity as most of us are used to a folder hierarchy.

**Comment by weeman1337** [comment]
Thanks for all the feedback. So it should be 1 board has 0/1 categories? Do we want to make it user dependent like @juliushaertl or is it bound to the board?

**Comment by nimishavijay** [comment]
It can be user dependent because that way it can be more flexible

**Comment by ilippert** [comment]
> Should it be 1 board left_right_arrow 0..1 category or 1 board left_right_arrow 0..* categories

I am coming late to this - just want to share a usecase: I see myself one of many people working in small organisations - in which we create projects (represented here in boards). These boards/projects often come with synergistic targets: they belong then to different categories. My specific use case is in academia: a literature review board can be part of the category "teaching" as well as "research on X" as well as "research on Y".

**Comment by weeman1337** [comment]
Closing that because it looks like it is still unclear what and how "categories" or "board grouping" should work.

The discussion can be found here #2006

**Pull request closed without merging**
