### PR TITLE
Created a raw german translation

### PR DESCRIPTION
**Pull request by ymybe**
It still uses the english gifs, mainly because i dont know how to produce my own and time is limited ;)

### CODE REVIEW

**Comment by ymybe** [comment]
tried again via terminal..

**Comment by ymybe** [comment]
look, i signed it...

**Comment by ymybe** [comment]
again i hope...

**Comment by ymybe** [comment]
i give up.

**Comment by juliushaertl** [comment]
That would still be really great to have, maybe you can give it another try in a fresh branch? Otherwise I'm also fine to merge without a signoff message since that is a documentation only change.

**Pull request closed without merging**
