### PR TITLE
Adjust notifier to Nextcloud 17

### PR DESCRIPTION
**Pull request by nickvergessen**
Ref nextcloud/server#15040

### CODE REVIEW

**Comment by MorrisJobke** [comment]
This needs a bump of the version requirement as well: https://github.com/nextcloud/deck/blob/master/appinfo/info.xml#L39

**Comment by juliushaertl** [comment]
Master is now stable17 only (which will be released as version 0.7 then)

**Comment by MorrisJobke** [comment]
> Master is now stable17 only (which will be released as version 0.7 then)

Feel free to merge then ;)

**Comment by juliushaertl** [comment]
Yep, just waiting for CI :wink:

**Pull request merged**
