### PR TITLE
[nc16-only] Implementing fulltextsearch

### PR DESCRIPTION
**Pull request by daita**
This will make the app fail on NC13/14, this needs to be on a specific version for NC16 (but should also works for NC15)

It does not catch the search from the searchbar within the deck app, but allow to search from the fulltextsearch app.

## ToDo
- [x] Fix tests
- [x] Test on 15/16
- [ ] Waiting for nextcloud/server#14905 nextcloud/appstore#602

### CODE REVIEW

**Comment by daita** [comment]
selection_064

**Comment by juliushaertl** [comment]
Thanks a lot @daita Looks good in general, will need to setup the fulltestsearch app to do some testing. Could you look into the test failures?

**Comment by juliushaertl** [comment]
@daita Any chance you can have a look at the failing tests? :wink:

**Comment by juliushaertl** [comment]
@daita Any news? I plan to push out a first beta at the end of the week, so it would be good to have this in there.

**Comment by juliushaertl** [comment]
- [ ] ./occ app:check-code $APP_NAME -c strong-comparison
Invalid appinfo.xml file found: Element 'provider', attribute 'min-version': The attribute 'min-version' is not allowed.
- [ ] Add EventDispatcherInterface to unit tests

**Comment by juliushaertl** [comment]
3ebe7949 needs to be reverted after https://github.com/nextcloud/server/pull/14905 has been merged

**Pull request merged**
