### PR TITLE
Stylelint fixes

### PR DESCRIPTION
**Pull request by juliushaertl**
- [ ] Figure out why CI is green but it fails locally
- [ ] Fix them

```
npm run stylelint

> deck@1.7.0-beta1 stylelint
> stylelint src


src/components/board/Board.vue
 164:32  ✖  Unexpected extension ".scss" in @import  scss/at-import-partial-extension
 165:31  ✖  Unexpected extension ".scss" in @import  scss/at-import-partial-extension

src/components/board/Stack.vue
 279:39  ✖  Expected single space before "*"        scss/operator-no-unspaced
 279:39  ✖  Expected single space after "*"         scss/operator-no-unspaced
 280:16  ✖  Unexpected unknown function "math.div"  function-no-unknown
 281:17  ✖  Unexpected unknown function "math.div"  function-no-unknown

src/components/card/CardSidebar.vue
 220:42  ✖  Expected single space before "*"          scss/operator-no-unspaced
 220:42  ✖  Expected single space after "*"           scss/operator-no-unspaced
 220:42  ✖  Expected single space after "*" operator  function-calc-no-unspaced-operator
 225:42  ✖  Expected single space before "*"          scss/operator-no-unspaced
 225:42  ✖  Expected single space after "*"           scss/operator-no-unspaced
 225:42  ✖  Expected single space after "*" operator  function-calc-no-unspaced-operator

src/components/card/Description.vue
 269:3  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule

src/components/cards/CardItem.vue
 235:3  ✖  Unexpected invalid position @import rule  no-invalid-position-at-import-rule

src/components/search/GlobalSearchResults.vue
 176:30  ✖  Unexpected extension ".scss" in @import  scss/at-import-partial-extension

src/components/search/Placeholder.vue
 58:30  ✖  Unexpected extension ".scss" in @import  scss/at-import-partial-extension
```

### CODE REVIEW

**Comment by juliushaertl** [comment]
Seems to be that for some reason when running this within the server codebase (apps/deck/) the node_modules from server change the result of the stylelint run. 😞 

On local setup:
- Deck cloned into apps/deck/
- Install dependencies: `npm ci`
- Run stylelint in deck: `npm run stylelint` -> ❌ 
- Delete node modules from server `rm -r ../../node_modules`
- Run stylelint in deck: `npm run stylelint` -> ✅ 

@skjnldsv Have you seen anything like that maybe already?

**Comment by skjnldsv** [comment]
Do you have some binaries installed globally?

**Comment by juliushaertl** [comment]
Nothing that I would consider causing this:

```
npm list -g
/Users/julius/.nvm/versions/node/v14.19.0/lib
├── corepack@0.10.0
├── npm-check-updates@12.4.0
└── npm@7.24.2
```

The odd thing is that the parent node_modules from server seems to cause that by just being present. 

Also `npx stylelint --print-config src` this on both CI and local: 
```
    "scss/at-import-partial-extension": [
      "never"
    ],
```

Just when node_modules in server is present this seems to get ignored.

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/deck/pull/3808

**Pull request closed without merging**
