### PR TITLE
Fix wrong SQL queries

### PR DESCRIPTION
**Pull request by Chartman123**
Add additional ', so that the resulting SQL query is correct

* Resolves: #2277 
* Target version: master 

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by Chartman123** [comment]
I've tested the fix on our Nextcloud and the error messages in the log files have gone.

**Review by stefan-niedermann — APPROVED** [review]

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks a lot for the fix :+1: 

Mind to add a signoff message to your commit? :)

**Comment by Chartman123** [comment]
> Mind to add a signoff message to your commit? :)

Sorry... Is it possible to change the commit message or how can I add the signoff message?

**Comment by juliushaertl** [comment]
You should be able to just signoff the last commit and do a force push with the following commands on your branch:

```
git commit --amend --signoff
git push -f
```

**Comment by Chartman123** [comment]
> You should be able to just signoff the last commit and do a force push with the following commands on your branch:
> 
> ```
> git commit --amend --signoff
> git push -f
> ```

Ok, so I'll have to install git first... I edited the file and created the PR online directly in GitHub

**Comment by Chartman123** [comment]
Apparently it worked ;-)

**Pull request merged**
