### PR TITLE
When creating a board, choose the less used color

### PR DESCRIPTION
**Pull request by rpadovani**
Fix issue #245 

I first tried a simple approach, trying to calculate which color using just counting how many boards there are. Of course this approach had a lot of issues, so I then tried to calculate which color was not used yet. While this works, what happens when all the colors have been used at least once?

Therefore I choose to make the approach the most generic possible, using the less used color and, if there was a draw, using the most left on the $scope.colors array.

This implementation should work perfectly also in future, if we change default colors or if we allow custom colors

Signed-off-by: Riccardo Padovani <riccardo@rpadovani.com>

### CODE REVIEW

**Comment by jancborchardt** [comment]
Thank you @rpadovani, nice contribution! :)

**Comment by jancborchardt** [comment]
@rpadovani also, I just saw you are based in Munich. You should come to our monthly Nextcloud meetups which are nice hack-meetings to sit together and work on improving Nextcloud: https://www.meetup.com/nextcloud-munich/ :) cc @Henni & @irgendwie from the meetup

**Comment by rpadovani** [comment]
@jancborchardt thanks for the invitation! I haven't joined so far because my German is still very bad - I am not able to talk, and as far as I can see the evenings are in German, aren't they?

**Comment by jancborchardt** [comment]
@rpadovani don't worry, @mabkenar is also there sometimes and speaks mainly English, and for @Henni and @irgendwie it's not a problem. ;) What counts is that you are a great contributor!

**Pull request merged**
