### PR TITLE
Inserted required property in the rename list field, to prevent the l…

### PR DESCRIPTION
**Pull request by mstolf**
When creating a list on the Deck, there is a validation requiring the name of the list to be informed

But when renaming a list, it was possible to keep it without a name, so I put the required field validation

* Resolves: #3861
* Target version: master 

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [x] Tests (unit, integration, api and/or acceptance) are included
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Usually my opinion is, that this is a *validation*, and validations belong into the backend (at least). Other clients will otherwise still be able to create / rename lists to `blank`.
On the other hand this was a breaking change of the REST-API and should be planned well therefore.

**Comment by mstolf** [comment]
@stefan-niedermann In this case I followed the list creation pattern, from what I saw it was treated on the front-end too, I understand that in this case the validation would be better on the back-end because it would not open room for errors

**Review by juliushaertl — APPROVED** [review]
Thanks for the pull request, I pushed a fix to also enforce this on the backend, so LGTM 👍

**Comment by stefan-niedermann** [comment]
@juliushaertl 

1. Will there be a database migration? (e. g. converting <kbd>Blank</kbd> to <kbd>Space</kbd>?)
2. How will the API respond to a request that contains <kbd>Blank</kbd>? `400`? `422`? Any proper error message?

**Comment by juliushaertl** [comment]
@stefan-niedermann The API will return a 400 Bad Request response as if the title was not set at all with the error message from https://github.com/nextcloud/deck/pull/3862/files#diff-8a98def6b971c75496456ec632f1310cd132642aa188861682457694b47b5096R218

**Pull request merged**
