### PR TITLE
new archive sidebar

### PR DESCRIPTION
**Pull request by jakobroehrl**
Signed-off-by: Jakob Röhrl <jakob.roehrl@web.de>
* Resolves: #1721
* Target version: master 

Cards are listed in the sidebar now:
grafik

### CODE REVIEW

**Comment by jakobroehrl** [comment]
@juliushaertl 
Do you have any idea why this is not working?
https://github.com/nextcloud/deck/blob/92e1d2798fedf16837c5ce9cd3dccf973fe37839/src/store/card.js#L93-L95 I don't get any cards back, thanks!

**Comment by juliushaertl** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find Have a look on what find does :wink:

**Comment by jakobroehrl** [comment]
@juliushaertl 
The Sidebar only shows card if I click on show archived cards in the top bar, why?

**Comment by juliushaertl** [comment]
>  The Sidebar only shows card if I click on show archived cards in the top bar, why?

Are they fetched already and in the store?

**Comment by juliushaertl** [comment]
I'm not sure about this from the UI perspective as it would mean that looking at a card would cause a loss of context since the sidebar switches to the card view then.

**Comment by jakobroehrl** [comment]
> I'm not sure about this from the UI perspective as it would mean that looking at a card would cause a loss of context since the sidebar switches to the card view then.

OK, what should I do? Implement it like this?
grafik

**Comment by juliushaertl** [comment]
> OK, what should I do? Implement it like this? 

Not sure what you mean with the screenshot. This won't help as then the board sidebar still switches to the card sidebar and you no longer see the context of archived cards.

**Comment by jakobroehrl** [comment]
We want to use a model for the card content, I will test it...

**Pull request closed without merging**
