### PR TITLE
Add min-height to card list and merge duplicate rules for .card

### PR DESCRIPTION
**Pull request by juliushaertl**
fix for #235 

also merging two .card declarations into one

### CODE REVIEW

**Comment by juliushaertl** [comment]
> The problem is not min height, but the fact that ul.card-list is the target for mouse cursor. Proper solution would be to use the entire div.stack as mouse target instead.

The problem is that the mouse target will be automatically assigned to the item that contains the list of sortable items (in our case the ul element). I could not find a solution for this right now.

If you want to have a look, feel free. Otherwise I'd like to merge this for now since it fixes a bug. :wink:

**Comment by juliushaertl** [comment]
>  I wonder what if we moved the "Add Card" button/form into the list (as always last element)

Let me check that later today. That sounds like it should work :wink:

**Comment by jancborchardt** [comment]
Any update @juliushaertl? Can help reviewing for sure :)

**Comment by pixelipo** [comment]
AFAIC, we can merge as-is and fix #239 in a separate PR

**Comment by juliushaertl** [comment]
> I wonder what if we moved the "Add Card" button/form into the list (as always last element)

That did not went well, becasue ng-sortable will then add a placeholder to drag to after the add button.

I did some margin/padding magic to make the drag-target container also include the header/create button. Please review @jancborchardt @pixelipo

**Comment by jancborchardt** [comment]
Which version was this fixed in? 0.2.2 I guess?  :)

**Comment by jancborchardt** [comment]
Asking cause I encounter that issue with the version of the Deck app at Portknox – cc @Gomez :)

**Comment by juliushaertl** [comment]
@jancborchardt Yes, it is in 0.2.2

**Comment by jacestk** [comment]
Mhh in 0.2.3 I stil can't move card into empty stack!

**Comment by juliushaertl** [comment]
@jacestk Works fine here with 0.2.3 and Nextcloud 12 on both firefox and chrome. Please try a hard reload to ensure that no files are cached (Ctrl +  F5). If it still doesn't work please open a new issue including details about your browser.

**Comment by jacestk** [comment]
Nope don't work on IE11, FireFOX 55.0.3 (64 bits), Chrome  61.0.3163.100 ...

**Pull request merged**
