### PR TITLE
Deck card comment notification label improvement

### PR DESCRIPTION
**Pull request by Jerome-Herbinet**
### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by nimishavijay — APPROVED** [review]

**Review by jancborchardt — COMMENTED** [review]
Seems good! Btw @Jerome-Herbinet since there are 3 settings related to Deck, it would make sense to group them together as a proper group outside of "Other activities" if Deck is enabled, right?

**Review by jancborchardt — APPROVED** [review]

**Comment by Jerome-Herbinet** [comment]
> Seems good! Btw @Jerome-Herbinet since there are 3 settings related to Deck, it would make sense to group them together as a proper group outside of "Other activities" if Deck is enabled, right?

You are right @jancborchardt and I thought about it but, to he honest, I don't know how to create a new category ... and how long and/or complex the development would be 🤔

**Comment by jancborchardt** [comment]
Maybe @nickvergessen can you point @Jerome-Herbinet in the right direction? :)

**Comment by nickvergessen** [comment]
Make the base class extend `OCP\Activity\ActivitySettings` and then set the group identifier and name like in:

https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/apps/dav/lib/CalDAV/Activity/Setting/CalDAVSetting.php#L43-L49

**Comment by juliushaertl** [comment]
Thanks for the pull request, I took over and pushed some adjustments to group the settings:

Screenshot 2023-08-22 at 08 10 44

**Review by juliushaertl — APPROVED** [review]

**Pull request merged**
