### PR TITLE
fix: Avoid optional before required parameter

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix https://github.com/nextcloud/deck/issues/5793

### CODE REVIEW

**Review by tflidd — APPROVED** [review]

**Review by joshtrichards — APPROVED** [review]

**Comment by joshtrichards** [comment]
@juliushaertl Can we do up a new release containing this fix? People keep reporting this even though we already fixed it. :-)

**Comment by PrzemekSkw** [comment]
Hello, issue is not fixed I see it still in 29.0.2 docker version.
Regards.

**Comment by joshtrichards** [comment]
@PrzemekSkw It has nothing to do with the Docker version or Nextcloud version. This app gets published through the app store.

**Comment by joshtrichards** [comment]
@PrzemekSkw This was already answered on the issue: https://github.com/nextcloud/deck/issues/5938#issuecomment-2156150544 (you can manually apply the patch)

**Pull request merged**
