### PR TITLE
Due date shortcuts

### PR DESCRIPTION
**Pull request by jakobroehrl**
* Target version: master 

Implemented like here: https://mengxiong10.github.io/vue2-datepicker/index.html#Shortcut 
But I see no shortcut in the Picker
grafik

@juliushaertl Do you have an idea what the problem could be? There are ne errors in the console.

### CODE REVIEW

**Comment by juliushaertl** [comment]
We do not support this in our vue components yet: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/DatetimePicker/DatetimePicker.vue

I'd suggest to open an issue over there and see if we can get a standardized way of the shortcuts in to the component itself.

**Comment by jakobroehrl** [comment]
@juliushaertl 
I could add to the card action menu 
 - Due: Today
 - Due: Tomorrow
 - Due: This week

This would be a very fast way to change the due date. What do you think about this?
grafik

**Comment by juliushaertl** [comment]
Not a huge fan of this, there is already quite a lot in the menu there and I'd rather keep it simple. We should not overload the UI with tons of options.

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/1419

**Comment by jakobroehrl** [comment]
https://github.com/nextcloud/deck/pull/2684

**Pull request closed without merging**
