### PR TITLE
Update Description.vue: Fixes the issue of hidden text by menu bar

### PR DESCRIPTION
**Pull request by pschopen**
* Resolves: #4621
* Target version: main

### Summary
Fixes the issue that tags were hidden by the text menu bar.

### TODO

- [ ] ...

### Checklist

- [ ] Code is properly formatted
- [ ] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included
- [ ] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Review by juliushaertl — APPROVED** [review]

**Comment by juliushaertl** [comment]
Thanks a lot for the pul request :)

**Comment by pschopen** [comment]
As this is a quite annoying bug for people actively using deck, it would imho make sense to release a fixed version soon...

**Pull request merged**
