### PR TITLE
Fix generated fronted urls

### LINKED ISSUE #1916: Linking causes invalid URL
When you link one card to another, the link points to the wrong address.

The linked url is:
.../cloud/index.php/apps/deck/#/board/6/**cards**/29

That would be right:
.../cloud/index.php/apps/deck/#/board/6/**card**/29

Thank you for your work!

### LINKED ISSUE #1922: Notifications about deck comments cannot go to the right card because there is a extra symbol into the link
**Describe the bug**
Deck Version: 1.0.1
When user open the notifications tools on nextcloud, and then clic over a comment about deck, the sistem redirect to a blank page, and not to the correct card. There is an (!) symbol in the URL that makes a incorrect link.

/deck/#/!/b

**To Reproduce**
1. User comment into a card on deck and make a mention to a user.
2. The user recive a notification, and try to open it.
3. When the user make a clik on the notification, the system redirect to a blank page and not to the correct card becausa an (!) symbol appears into the link, like:
www....com/index.php/apps/deck/#/!/board/93/card/925
when the correct link is:
index.php/apps/deck/#/board/93/card/925
4. Its imposible to open directly a card through the notifications.

**Expected behavior**
The user can make a clic on a notification, and the system redirect to the card commented.

**Screenshots**
image
image

**Client details:**
 - OS: Windows 10
 - Browser Chrome
 - Version Lastest
 - Device: Windows Desktop

<details>
<summary>Server details</summary>

**Operating system**:

**Web server: Nextclud Deck 18.0.4
**List of activated apps:**

Enabled:
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_pdfviewer: 1.7.0
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - groupquota: 0.1.2
  - impersonate: 1.5.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - theming: 1.9.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

**Nextcloud configuration:**
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 0
    }
}

or

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

ActiveDirectory

### PR DESCRIPTION
**Pull request by juliushaertl**
Fix #1916
Fix #1922

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
We have a *share card url" button in the android app. Are you aware of any change of the URL format across the different server versions?

**Comment by aszlig** [comment]
Doesn't this miss [OCA\Deck\Activity\DeckProvider::deckUrl](https://github.com/nextcloud/deck/blob/1d589fe3e6f5117a246671eb3ceb98728b112501/lib/Activity/DeckProvider.php#L360) or are those bang-prefixed URL fragment identifiers still recognised?

**Comment by juliushaertl** [comment]
> We have a share card url button in the android app. Are you aware of any change of the URL format across the different server versions?

Yeah, unfortunately there is not much we can do there since vue-router has removed the support for the hashbang prefixing. Maybe we should provide a server side unique link to cards that can then adapt to whatever the frontend is doing (similar to the files apps /f/{fileid}).

> Doesn't this miss OCA\Deck\Activity\DeckProvider::deckUrl or are those bang-prefixed URL fragment identifiers still recognised?

Ah nope, good catch.

**Comment by stefan-niedermann** [comment]
> Yeah, unfortunately there is not much we can do there since vue-router has removed the support for the hashbang prefixing.

Okay, so there actually is a change. Can you please tell me how the link looks across the different server app versions, for example:

```
0.0.1 - 0.8.1: example.com/apps/deck/#!/board/5/card3
0.8.1 - 1.0.0: example.com/apps/deck/app/#!/board/5/card3
>= 1.0.1:      example.com/apps/deck/board/5/card3
```

Then i am able take care that copying URLs will work with each server version.

> Maybe we should provide a server side unique link to cards that can then adapt to whatever the frontend is doing (similar to the files apps /f/{fileid}).

This makes sense to prevent broken bookmark links. But you should ensure that this won't result in additional request with a redirect for the web UI users.

**Comment by juliushaertl** [comment]
See https://github.com/nextcloud/deck/pull/1977 for the details and a fallback for the old routes.

**Pull request merged**
