### PR TITLE
Add length documentation for title attributes in the API documentation

### PR DESCRIPTION
**Pull request by juliushaertl**
https://github.com/nextcloud/deck/issues/1344#issuecomment-616396716

### CODE REVIEW

**Comment by stefan-niedermann** [comment]
Okay, so

- Titles of Stacks and Boards is now limited to `100` characters, that's fine
- Titles of Cards are now extended to `255` characters, that's a breaking change

If a client sends a title with `255` characters to an older version of the Deck API, it will probably break with some kind of SQL-error, because it was previously limited to `100` characters, won't it?

**Comment by juliushaertl** [comment]
> Titles of Cards are now extended to 255 characters, that's a breaking change

Well kind of, but with the old release exceeding the character limit would always cause an exception, that is why i considered it a bugfix. :wink:

**Comment by stefan-niedermann** [comment]
Bugfix: maybe. But this doesn't change that **this is a breaking change**. You only have to support one API version at your frontend, 3rd-party-clients must be able to handle multiple different versions.

For example here two problematic szenarios:

1. New version gets installed. Android client doesn't change anything, user enters a title > `100` characters via web interface
Best case: Title gets truncated at next sync to 100 characters, worst case: somewhere a SQL-exception get's thrown, because a client has a `VARCHAR(100)` type for this column. damnation. doom. death.

2. Old version stays installed. Android client changes the title limit to `255`, user enters a title > `100` characters via android app
Server responds, that the title cannot be accepted

We have to make a differentiation of the available server API in any case.

**A breaking change is fine and absolutely valid for a new major version. But we need to know about breaking changes so we can *handle* them. Otherwise it would cause strange errors which are badly reproducible and to mad users asking for support :wink: .**

**Comment by juliushaertl** [comment]
Agreed, yes I'll try to improve communication in that regards. 

In theory we also have an API version in the URL which is currently hardcoded to 1.0, so we could also use that to push breaking changes, but I'd generally prefer to just make this depend on the app major/minor release version and put the changes in a proper log. Would that work for you?

**Comment by stefan-niedermann** [comment]
Thank you, yes, i agree (we already have the server app version logic and i would like to avoid to handle another version.

So, which server version will contain this change? 1.0.0?

**Comment by juliushaertl** [comment]
Yes, 1.0.0 will be the first stable release to contain this (it can already be tested with the beta releases). I#ve also pushed a commit to list the two changes that could affect you for now. I'll keep that updated then and mention you if new changes come up.

**Pull request merged**
