### PR TITLE
redesign stack context menu

### PR DESCRIPTION
**Pull request by artemanufrij**
Signed-off-by: Artem Anufrij <artem.anufrij@live.de>

### CODE REVIEW

**Comment by artemanufrij** [comment]
Fix for #170

**Comment by juliushaertl** [comment]
@artemanufrij Nice. One small adjustment, I think the 3-dots button should be in the same column alignment as the ones from the card.
2017-05-31-093538_62x158_scrot

**Comment by artemanufrij** [comment]
@juliushaertl ok... I will change it. my focus was on right margin.

**Comment by pixelipo** [comment]
@juliushaertl I'm not so sure these should be aligned. After all, card is visibly narrower than stack.

**Comment by artemanufrij** [comment]
We can hide "..." - button if cursor is out of card/stack. currently it has opacity: 0.25.

**Comment by artemanufrij** [comment]
fixed in #173

**Pull request closed without merging**
