### PR TITLE
Added ability to mark a card as done

### PR DESCRIPTION
**Pull request by TehThanos**
* Resolves: #534 
* Target version: stable24

### Summary
This adds the ability to mark a card as done.
When the card is marked as done if it has a due date then it makes it un-editable, if it doesn't it simply displays "No due date" 
Marking a card as done also hides it from the upcoming section.
### TODO

- [x] BUG: When you mark/unmark a card as done, the assigned user(s) get set to null (only on the frontend)
- [x] BUG: Menu card doesn't update the mark "done"/"not done" option when the status changes

### Checklist

- [x] Code is properly formatted
- [x] Sign-off message is added to all commits
- [ ] Tests (unit, integration, api and/or acceptance) are included (**Help wanted, I get errors not matter if I include my code or not**)
- [x] Documentation (manuals or wiki) has been updated or is not required

### CODE REVIEW

**Comment by juliushaertl** [comment]
Wow, nice great to see this as a contribution coming. While I haven't looked in detail at the code yet, could you base your changes on the master branch? New features only get merged to master for the next release.

**Comment by stefan-niedermann** [comment]
Nice contribution 🙂 🚀 

Please also keep in mind the Rest API:
- Can this be implemented fully backward compatible?
- Will there be a separate REST endpoint for marking a card as `done` / `undone` or will it be just an additional property of the `Card` entity?
- Documentation for deck.readthedocs.io

**Comment by TehThanos** [comment]
> Wow, nice great to see this as a contribution coming. While I haven't looked in detail at the code yet, could you base your changes on the master branch? New features only get merged to master for the next release.

Uh sorry will do should I close this pr?

**Comment by TehThanos** [comment]
> Nice contribution slightly_smiling_face rocket
> 
> Please also keep in mind the Rest API:
> 
> * Can this be implemented fully backward compatible?
> * Will there be a separate REST endpoint for marking a card as `done` / `undone` or will it be just an additional property of the `Card` entity?
> * Documentation for deck.readthedocs.io

Thanks! :D

1. I believe so although I do check the code a bit more
2. They are 2 separate endpoints, I saw archive was like that so I just copied that, let me know if I should change it
3. I user docs are done but I do need to do the docs for the API

**Comment by juliushaertl** [comment]
> Uh sorry will do, should I close this pr?

Feel free to either close and open a new pull request or rebase the branch and [change the base branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request).

**Comment by TehThanos** [comment]
Cool I'm just gonna close this and open a new one for master then.

**Pull request closed without merging**
