### PR TITLE
Use separate preview for description and allow toggling checkboxes

### PR DESCRIPTION
**Pull request by juliushaertl**
image

Fixes https://github.com/nextcloud/deck/issues/1673 and parts of https://github.com/nextcloud/deck/issues/1709

### CODE REVIEW

**Comment by jakobroehrl** [comment]
@juliushaertl what is the markdown code to generate a checkbox?

**Comment by putt1ck** [comment]
The use of 2 square brackets with a space between is how the old editor did it (and also I think github MD) [ ] `[ ]`

**Comment by jakobroehrl** [comment]
> 
> 
> The use of 2 square brackets with a space between is how the old editor did it (and also I think github MD) `[ ]`

Tried it so, doesn't work for me.

**Comment by stefan-niedermann** [comment]
`- [ ]`

try `minus space bracket space bracket`

**Comment by putt1ck** [comment]
> > The use of 2 square brackets with a space between is how the old editor did it (and also I think github MD) `[ ]`
> 
> Tried it so, doesn't work for me.

Testing on v1b1, the card view shows a check list when I add something like

[ ] an item
[ ] another item

(at this point the card shows a :white_check_mark: 0/2)

But the view of description continues to show just `[ ] an item` and the only way to check one is replace the space with an x

**Comment by putt1ck** [comment]
> `- [ ]`
> 
> try `minus space bracket space bracket`

I tried that, which makes it autolist while editting (useful :) ) but still doesn't render in a way that allows a user to mark the check box by clicking it.

**Comment by juliushaertl** [comment]
> I tried that, which makes it autolist while editting (useful :) ) but still doesn't render in a way that allows a user to mark the check box by clicking it.

This is what this pull request implements for the preview mode. However there is still a small issue, since the library we use for checkmarks in markdown only supports list style checkboxes `- [x]` not independent ones `[x]`, so we need to adjust the regex for the card badges as I don't see a way to support both right now.

**Comment by juliushaertl** [comment]
Peek 2020-04-21 08-35

**Comment by jakobroehrl** [comment]
OK, this is the way it works:
- [ ] x
- [x] x

**Pull request merged**
