### PR TITLE
edit board in board list view

### PR DESCRIPTION
**Pull request by artemanufrij**
Signed-off-by: Artem Anufrij <artem.anufrij@live.de>

### CODE REVIEW

**Comment by artemanufrij** [comment]
fix for #183 
screenshot_20170620_202955

**Comment by juliushaertl** [comment]
Nice, although i would prefer hide the 3 dots menu and just show a confirm/cancel button there at the end of the line.

**Comment by artemanufrij** [comment]
screenshot_20170620_230016

**Comment by artemanufrij** [comment]
Add new board:
screenshot_20170621_224212

**Pull request merged**
